###
GET http://localhost:9192/ticketapp/api/ HTTP/1.1

###
GET http://localhost:9192/ticketapp/api/Jan2022/ HTTP/1.1

###
GET http://localhost:9192/ticketapp/api/months/ HTTP/1.1

###
GET http://localhost:9192/ticketapp/api/resolution/Supplier=Customer+Migration=Numbering+Plan+Change+Request/ HTTP/1.1

###
GET http://localhost:9192/ticketapp/api/all/resolutions/ HTTP/1.1

###
GET http://localhost:9192/ticketapp/api/ticket/10034041/ HTTP/1.1

### 
PUT http://localhost:9192/ticketapp/api/ticket/ HTTP/1.1
Content-Type: application/json

{
    "APP_NM": "REPC",
    "TICKET": 10034055,
    "RESOLUTION": "Application Latency",
    "TICKET_TYPE": "Incident",
    "COMMENT": "User created contention",
    "CREATED_ON": "2022/02/21 05:40:14",
    "MON": "Feb2022",
    "RESOLVED_BY": "Harish"
}